CREATE DATABASE REGISTROS;

USE REGISTROS;

CREATE TABLE USERS(
CORREO VARCHAR(30) NOT NULL primary key,
NOMBRES VARCHAR(15) NOT NULL,
APELLIDOS VARCHAR(50) NOT NULL,
PASS varchar(20) NOT NULL  
);

INSERT INTO USERS VALUES('ALGO@GMAIL.com', 'ERICK', 'LUNA',NULL);

select * from users